### PR TITLE
Feature/multiple preview

### PR DESCRIPTION
**Pull request by Maratripa**
# Feature
Allow the use of [wildcards](https://en.wikipedia.org/wiki/Wildcard_character#Computing) to display more than one image.

## Examples
```bash
pic -p iterm ~/Pictures/*.jpg
```
to display all `.jpg` images inside the `Pictures` directory.

```bash
pic ./*/*.png
```
to display all `.png` images inside any directory with depth 1 relative to pwd.

## TODO
- [ ] Display all image files if a directory is selected in path (Probably another PR)
- [ ] Allow grid display of images (Another PR, big changes)

### CODE REVIEW

**Comment by emsquid** [comment]
That's great work, how do you think this should work when specifying arguments as `--x`and `--y` ? Won't all images get over themselves ?

**Comment by Maratripa** [comment]
Just tested, -x does not affect as it just moves all images by an offset. -y does make the images overlap each other.
What do you think would be the intended result here? 

For example, if I pass the flag `-y 3`, what should happen? 
- One possible thing is to make the `-y` flag useless if more than one image is requested.
- Other is to make the `-y` flag a "spacing" flag between images (This would be harder imho)

**Comment by emsquid** [comment]
Sounds good to me, for kitty protocol to work as you intend we would need to use different IDs, or we could use the uppercase I flag if I am not wrong, I know a bit about it so I should be able to deal with it

**Comment by emsquid** [comment]
I was thinking of doing that with caching, we could store tempfiles in some repertory like `.cache/pic` or something, and not delete them so that we don't need to open the image each time (idk how we could name them to keep them unique and yet remember them), atm the tempfile is immediately being deleted by Kitty because it is not required anymore (Kitty loads the image in its memory, but if it's loaded without id it doesn't remain, there is a flag we can use so that it loads it with a random available id, see [here](https://github.com/kovidgoyal/kitty/blob/master/docs/graphics-protocol.rst#requesting-image-ids-from-the-terminal)

**Comment by emsquid** [comment]
It would be great if we could keep track of image ids, much more efficient, it's so fast once the image is loaded

**Comment by Maratripa** [comment]
Maybe we remove the option to set IDs manually and set up a hash the image path + unique options (What I mean by this is that I don't know if kitty sets up width and height of the image after loading from memory or it saves it to memory with some width and height) so if I run `pic` with the same arguments as before, kitty just loads the hashed ID.

**Comment by emsquid** [comment]
The power of kitty is that it once an image is loaded it can display it anywhere and resize it super quickly, the image is not stored with a fixed memory (kitty is the protocol I developed the most because I was only using this one in the beginning).
On the one hand your idea really seems good if we can figure a way to implement it, it could make kitty even better if well done. 
But on the other hand the problem is the fixed options, with kitty (you can try) it will make it less efficient than loading and then displaying.
I already had some thought about that but I didn't want to make some shenanigans implementations... It's up to your imagination as of now, I like your ideas overall, and I will also tell you if something displease me, so try everything you have in mind we are not open source for nothing ;)

**Comment by Maratripa** [comment]
TODO
- [ ] Create cache dir if it does not exist
- [ ] When receiving a path, check if it is cached (Do nothing for the moment)
- [ ] After using kitty protocol, create a file to create hashmap of FILE_PATH:ID
- [ ] If using kitty and file is cached, load the image with the ID
- [ ] After displaying image with kitty, modify cache dir with the image_path and modify file with NEW_PATH:NEW_ID
- [ ] Somehow make this work?

**Comment by emsquid** [comment]
I'm only wondering how we will get image ids, other than that it seems perfect to me, that's likely the way I would do it, but I couldn't figure a way to remember ids

**Comment by Maratripa** [comment]
For what I read in the link you sent, if we use the parameter `I` for kitty, it will reply with a valid `i` parameter and use that one to store the image. We need a way to get the response from kitty and store that `i` value as the ID.

**Comment by emsquid** [comment]
> For what I read in the link you sent, if we use the parameter `I` for kitty, it will reply with a valid `i` parameter and use that one to store the image. We need a way to get the response from kitty and store that `i` value as the ID.

Getting that id should be doable, look at the method to check if kitty protocol is supported, it should be approximately the same

**Comment by Maratripa** [comment]
To where  this is going, I think we should make cache feature in another pr. I'm going to try to get kitty to display multiple files quick ~and dirty~ and then move to another branch, because this feature is almost done. :)

**Comment by emsquid** [comment]
Let's do this I will merge it when it's done, I should try to implement GIFs with kitty one day too, welp we will clean that later.

**Comment by Maratripa** [comment]
Sadly, I don't seem to be able to display more than one image at a time with kitty protocol...

**Comment by emsquid** [comment]
> Sadly, I don't seem to be able to display more than one image at a time with kitty protocol...

That's weird, I will look into it tomorrow and give it a try after school!

**Comment by emsquid** [comment]
@Maratripa did you try to use the `I` parameter, I tried it quickly and it seems to work fine for me, we doesn't care about the id it returns for now but it's enough to display several images, isn't it ?

**Pull request merged**
